language: php

before_install:
  - git submodule update --init
  - composer install

matrix:
  include:
  - dist: precise
    php:
      - "nightly"
      - "7.1"
      - "7.0"
      - "5.6"
      - "5.5"
      - "5.4"
      - "5.3"  
  - dist: trusty
    php:
      - hhvm-3.3
      - hhvm-3.6
      - hhvm-3.9
      - hhvm-3.12
      - hhvm-3.15
      - hhvm-3.18
      - hhvm-nightly
      - "nightly"
      - "7.1"
      - "7.0"
      - "5.6"
      - "5.5"
      - "5.4"

branches:
  only:
    - master
    - develop

script: php test.php

matrix:
  allow_failures:
  - php: "nightly"
  - php: "hhvm-nightly"

